### PR TITLE
AISDK-104: Clarify mentions of balance in Python SDK

### PR DESCRIPTION
**Pull request by KostasRev**

### CODE REVIEW

**Review by k-weng — APPROVED** [review]
:shipit:

**Comment by k-weng** [comment]
Actually there are still other mentions of `balance` that should be changed - https://github.com/revdotcom/revai-python-sdk/search?q=balance&unscoped_q=balance

**Review by JohnDonavon — APPROVED** [review]
:shipit: Assuming this is the only mention

**Comment by KostasRev** [comment]
> Actually there are still other mentions of `balance` that should be changed - https://github.com/revdotcom/revai-python-sdk/search?q=balance&unscoped_q=balance

We are not changing any actual code or param names. Only descriptions.

**Pull request merged**
